### ISSUE TITLE
Unrelated issue

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [SQLite-DNA/SqliteDna#1]
Hi @govert Unsure how to reach out to you, so I'm creating an issue :-) I wrote a SQLite visualizer for the VS debugger years ago. I was using for an internal project but seeing your work over the years you might find it useful too. It can be found at https://github.com/microsoft/VSSDK-Extensibility-Samples/tree/master/SqliteVisualizer. Unsure its current state, but it was really helpful for me at the time.

**Comment by govert** [comment]
Hi @AaronRobinsonMSFT - thank you for the pointer to the visualizer.

I was very impressed with how smoothly DNNE works!
