### ISSUE TITLE
Rename [Function] -> [SqliteFunction]

### ISSUE THREAD

**Issue by govert** [SQLite-DNA/SqliteDna#2]
Even though it's in a SqliteDna namespace, it feels like `Function` is too generic.

```
        [SqliteFunction]
        public static int Foo2()
        {
            return 2;
        }
```

**Comment by govert** [comment]
I should note that there is also `System.Data.SQLite SQLiteFunctionAttribute` in the .NET provider.

**Comment by Sergey-Vlasov** [comment]
I've renamed [Function] -> [SqliteFunction].
